 sonar.projectKey=Onglink_Onglink_Backend
        sonar.organization=onglink

        sonar.sources=src
        sonar.tests=test
        sonar.javascript.lcov.reportPaths=coverage/lcov.info
        sonar.coverage.exclusions=src/config/**, src/routes/**, src/app.ts, src/server.ts